#!/bin/sh

set -e

date -u
echo "Updating adblock blocklists..."

cd /etc/adblock/blocklists

git fetch --all
git reset --hard origin/master

curl --unix-socket /var/run/docker.sock -X POST http://docker/containers/adblock-
dnsmasq/restart

echo "Done!"
echo

exit 0
